# Eredita dal tema base di Keycloak
parent=base

# Nome del tema
name=Errevi

# Quale tema padre usare (base è il default)
import=common

# Stili personalizzati
styles=css/style.css
scripts=js/custom.js

# Specificare feature
features=internationalization